### ISSUE TITLE
cellery build command usage is wrong

### ISSUE THREAD

**Issue by afkham** [wso2-cellery/sdk#101]
Usage:
 cellery build <cell-file> [flags]

As per that, only the cell file is mandatory. But if you run that command, you will find that the -t <organization>/<cell-image>:<version> is also mandatory. 

So usage should be:

cellery build <cell-file> <org> <cell-image> <version>

**Comment by sinthuja** [comment]
Fixed as per the last comment by madhuka. Thanks for the contribution @MadhukaHarith92
