### ISSUE TITLE
Add light weigh IDP to cellery system

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#128]
**Description:**
A lightweight IDP is required for cellery system components such as APIM, and observability to provide access control. This will also be used by Global Web Gateway to provide the SSO flow.

**Comment by hasinthaindrajee** [comment]
Fixed with [1]. Created a carbon server with minimal installation of Framework, OAuth and DCR

[1] https://github.com/wso2-cellery/mesh-security/commit/70c97f1d0024eced6d1f7b0b802646f93b133179
