### ISSUE TITLE
Unauthenticated API support

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#129]
**Description:**
Currently, all APIs published has security enabled by default, and hence the APIs cannot be invoked without generating an access token. This feature supports to expose a secured API to the external systems, therefore it can be invoked without any token.

**Comment by hasinthaindrajee** [comment]
This is done from STS side. Have to come up with proper syntax

**Comment by hasinthaindrajee** [comment]
For syntax the issue this is supported with https://github.com/wso2-cellery/sdk/pull/189
From cell gateway STS this implemented with https://github.com/wso2-cellery/mesh-security/commit/ba700b5afd9b9ebc4623e1e64a5b5db485a52318
