### ISSUE TITLE
Support for cellery run --start-dependencies

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#130]
**Description:**
Cellery run commands will start the instance of an image, and optionally users can provide the list of depending cell instance names as command line arguments. If the dependent instances are not up and running, then cell instance cannot be started, and it will fail. Therefore we introduce --start-dependencies flag to start the dependencies recursively if those are not already started, before starting the intended cell.

**Comment by nadundesilva** [comment]
Support should be provided to pass environment variables to specific Cells in the dependency tree as well. This would allow the user to selective provide environment variables to instances using `-e`flag.
