### ISSUE TITLE
Improvements to the current celelry syntax

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#132]
**Description:**
This includes below improvements
- Remove ballerina.io package from cellery init file
- APIDefinition struct, read swagger file and generate API Defintion
- Rename HttpApiIngress
- Remove 'public' from access modifiers
- Rename exposeGlobalAPI -> exposeGlobal
- Rename exposeIngressFrom -> exposeLocal"

**Comment by anuruddhal** [comment]
Fixed via 
- https://github.com/wso2-cellery/sdk/pull/123
- https://github.com/wso2-cellery/sdk/pull/118
