### ISSUE TITLE
Graphical view of cell images to show the dependencies

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#135]
**Description:**
Once the cell images are built, the users should be able to graphically visualize the cells it's depending on, and the components within the cell. This also should be possible with the cell images that were pulled from cellery repository.

**Comment by nadundesilva** [comment]
Added the skeleton on top of which the UI could be built upon in #124

**Comment by Minoli** [comment]
Graph and functionalities added with https://github.com/wso2-cellery/sdk/pull/158, https://github.com/wso2-cellery/sdk/pull/168 and https://github.com/wso2-cellery/sdk/pull/169

**Comment by nadundesilva** [comment]
Added support to open up the Graphical View in the default browser using `cellery view <image>` command in #171
