### ISSUE TITLE
[CLI] Cellery list ingress should work for image name as well

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#155]
**Description:**
Cellery list ingress should work for both image name and instance name as well, and currently it only supports ingress name. When listing the ingress with image name, we can only list the type of the ingress in the components different components,ingress name,port, basePath, etc.

**Comment by MadhukaHarith92** [comment]
Fixed in https://github.com/wso2-cellery/sdk/pull/179

**Comment by nadundesilva** [comment]
Closing as per the above comment
