### ISSUE TITLE
[CLI] Support to pass the system variable name as org/image/version when building and running

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#180]
**Description:**
Currently in cellery build and run, we can pass the image names. And during this we should be able to use the system variable to prepare the image name. For example, I should be able to build the image as below, and here org, and image are the two system variables. 

```bash
cellery build ${org}/${image}:1.0.0
```

Resolving the image name should be applied for all CLI commands where ever we take image name as input, and not only in the build/run. (ie, cellery push, pull, list, etc commands also should have this effect)

**Comment by sinthuja** [comment]
This is some what required for katacoda scenarios where users will need to build the images, and push it to their docker hubs.

**Comment by xlight05** [comment]
as we discussed offline, Cellery CLI has the functionality to accept env variables as a parameter. We can close this issue. @sinthuja
