### ISSUE TITLE
Cellery version command returns "unknown" for Cellery properties

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#183]
**Description:**
Cellery version commands returns "unknown" for most CLI version, built time, etc. 

ellery version
Cellery:
 CLI Version:		unknown
 Built:			unknown
 Git Commit:		unknown
 OS/Arch:		darwin/amd64

**Comment by Mirage20** [comment]
Are we going to remove Build time and GitHash from the version command?
Those values are populated when building the executable when you build the cli with `make build-cli` so we dont need to hardcode version info in the code.
