### ISSUE TITLE
Print "✔ Successfully installed Cellery runtime." even after cleanup fail

### ISSUE THREAD

**Issue by madushajg** [wso2-cellery/sdk#288]
**Description:**

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Mac OS 10.14.3

**Steps to reproduce:**
point to a non-existing cluster
cellery setup > 
✔ Manage
✔ Local
✔ BACK
✔ Existing cluster
✔ cleanup
✔ Yes
✔ Yes
✔ Yes

**Related Issues:**

**Comment by tharindulak** [comment]
When I am cleaning up my existing cluster I am getting 
✔ Successfully installed Cellery runtime.
Full log would look like
✔ Existing cluster
✔ cleanup
✔ Yes
✔ Yes
✔ Yes
✔ Cleaning up cluster

✔ Successfully installed Cellery runtime.
