### ISSUE TITLE
Cellery status <cell-instance-name> shows unexpected output after cell termination

### ISSUE THREAD

**Issue by azinneera** [wso2-cellery/sdk#328]
**Description:**
ATM, when the `cellery status` is run immediately after the `cellery terminate <cell-instance-name>` command, it exits with an exit code of 1. The expected exit code is 0 with the message `Cannot find cell: <cell-instance-name>` instead.

The cli should make sure that all resources has completely destroyed when `cellery terminate <cell-instance-name>` is given.

**Comment by MadhukaHarith92** [comment]
Discussed and changed the expected behavior as follows.
Cellery status should check if the cell exists. If cell is not found, an error message should be printed.
eg :Error running cell status: cannot find cell wso2cellery-pet-be-cell
No change in cellery terminate command at the moment.
