### ISSUE TITLE
Cannot execute cellery run from certain directory paths.

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#354]
Steps to reproduce:
1) I wasn't having ballerina installed before, and I was able to build/run hello world cell successfully.
2) I installed ballerina 0.990.3 
3) My samples code is checked out into ~/wso2/sources/dev/git/sinthuja/wso2-cellery/samples, and I built the hello world cell in ~/wso2/sources/dev/git/sinthuja/wso2-cellery/samples/hello-world location. and build was successful.
4) I tried to run the cell by being in the same directory ( ~/wso2/sources/dev/git/sinthuja/wso2-cellery/samples/hello-world), and now the run fails with below error.
✔ Extracting Cell Image sinthuja/hello-web:0.2.1

Main Instance: hello-web-0-2-1-76a819e3

✔ Reading Cell Image sinthuja/hello-web:0.2.1
✔ Validating dependencies

Instances to be Used:

       INSTANCE NAME                CELL IMAGE          USED INSTANCE   SHARED
 -------------------------- -------------------------- --------------- --------
  hello-web-0-2-1-76a819e3   sinthuja/hello-web:0.2.1   To be Created    -

Dependency Tree to be Used:

 No Dependencies

? Do you wish to continue with starting above Cell instances (Y/n)?

error: you are trying to run a ballerina file inside a module within a project. Try running 'ballerina run <module-name>'

Failed to start Cell instance hello-web-0-2-1-76a819e3: failed to execute run method in Cell instance hello-web-0-2-1-76a819e3 due to exit status 1
5) Once I step back to directory ( ~/wso2/sources/dev/git/sinthuja/wso2-cellery/samples/) it works.

**Comment by sinthuja** [comment]
Based on the discussion with @gnudeep , this issue arises because of the .cellery, and .ballerina directory created when running the ballerina as containers with the current directory. As a workaround, I can delete those directories in ~/wso2/sources/dev/git/sinthuja/wso2-cellery/samples/hello-world and try to run.

**Comment by gnudeep** [comment]
Changed the source mount path the /home/cellery/src. Now unwanted dot folders are not created.
