### ISSUE TITLE
Reduce the APIM startup time

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#359]
Currently the APIM startup time is 120+ seconds, and it's heavily influencing the overall startup time in the cellery setup. We need to investigate on the possible reasons and remove any unwanted delays.

**Comment by isurulucky** [comment]
Changes done: 

- Remove non-required call to internet in the p/r [1].
- Turn off advanced throttling in the local pre-built setup in the p/r [2]. 

[1]. https://github.com/wso2-cellery/distribution/pull/98
[2]. https://github.com/wso2-cellery/distribution/pull/99
