### ISSUE TITLE
Improve cellery to use Ballerina docker image to build and run cell files

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#360]
In 0.2.0 release we required to have the ballerina 0.990.3 installation to build and run cells. Therefore, we required to package the ballerina and java with the cellery installer. In order to solve this additional step and allow users to quickly get started with cellery, we need to spawn the ballerina docker images for this purpose.

**Comment by gnudeep** [comment]
Added docker based cli support.
