### ISSUE TITLE
Cellery build after installing ballerina fails

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#415]
Steps:
1) I ran cellery run without ballerina and encountered the issue - https://github.com/wso2-cellery/sdk/issues/414
2) Now installed ballerina version - 0.991.0, and re ran the cellery run and getting below error. 

cellery build stocks.bal myorg/stock:1.0.0
❌ Building image myorg/stock:1.0.0

Build Failed.
======================
error: failed to compile file: native function not available celleryio/cellery:0.0.0:createCellImage

Error occurred while building cell image: exit status 1
-- Expected behaviour:
We need to check for ballerina installation, and copy the cellery module if it's missing. I think @isurulucky did a fix sometime back for this, and it seems not working now. Have removed it?

**Comment by anuruddhal** [comment]
Resolved with https://github.com/wso2-cellery/sdk/pull/420
