### ISSUE TITLE
Include support for other metrics in the ballerina syntax for auto scaling

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#429]
Currently it only supports the cpu percentage, and we also should include support for actual value of cpu as well. Also we should add memory related metrics, both percentage and actual value.

**Comment by isurulucky** [comment]
AFAIU we decided to support only CPU related metrics for 0.3.

**Comment by sinthuja** [comment]
I was thinking that it will not be a big change, and hence thought of including it for the sake of completeness. @anuruddhal can work on the syntax related changes, and hence I think there should be very limited changes for controller to accommodate this.

**Comment by isurulucky** [comment]
PR with proposed changes for the SDK: https://github.com/wso2-cellery/sdk/pull/466
