### ISSUE TITLE
Remove enable-autoscaling flag from cellery-config, and have the autoscaling enabled by default always

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#431]
Currently the autoscaling is disabled by default with the above configuration. As that was an experimental feature, we had it disabled before. But with 0.3, we should remove this flag completely.

**Comment by isurulucky** [comment]
@sinthuja as per the discussion we had, shall we leave this flag as it is but set the default value to true?

**Comment by sinthuja** [comment]
Ok,+1.

**Comment by isurulucky** [comment]
This flag is turned on by default in PRs https://github.com/wso2-cellery/mesh-controller/pull/87 and https://github.com/wso2-cellery/distribution/pull/122.
