### ISSUE TITLE
Validate metrics-server and k-native installation exist with auto scaling configurations

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#433]
As the metrics-server, and K-native is optional for the users, and they can install that with modify setup as per https://github.com/wso2-cellery/sdk/issues/432, before we run a cell, the cellery CLI should validate whether the metrics-server and k-native installation exist, if autoscaling policy is added to the component. If not, the warning should be printed.

**Comment by anuruddhal** [comment]
Shouldn't we fail the run command instead of printing a warning?

**Comment by sinthuja** [comment]
As we discussed offline, for zero-scaling let's fail the run. But for auto-scaling, let's print a warning.
