### ISSUE TITLE
HPA is getting created for component without any autoscaling policy

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#436]
I was testing the employee portal, and I have added auto scaling policy for only employee cell components, and not for hr and stock. But when I list the hpa, all components have got the hpa created, which is not required if there is no autoscaling policy in the component definition.
```
kubectl get hpa
NAME                                     REFERENCE                                  TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
employee--employee-autoscalepolicy-hpa   Deployment/employee--employee-deployment   3%/10%          1         3         3          4m15s
employee--gateway-autoscalepolicy-hpa    Deployment/employee--gateway-deployment    5%/80%          1         1         1          4m44s
employee--salary-autoscalepolicy-hpa     Deployment/employee--salary-deployment     2%/10%          1         3         3          4m15s
hr--gateway-autoscalepolicy-hpa          Deployment/hr--gateway-deployment          <unknown>/80%   1         1         1          2m10s
hr--hr-autoscalepolicy-hpa               Deployment/hr--hr-deployment               2%/80%          1         1         1          2m9s
istio-pilot                              Deployment/istio-pilot                     <unknown>/80%   1         5         0          4d20h
stock--gateway-autoscalepolicy-hpa       Deployment/stock--gateway-deployment       6%/80%          1         1         1          4m46s
stock--stock-autoscalepolicy-hpa         Deployment/stock--stock-deployment         3%/80%          1         1         1          4m46s

```

**Comment by isurulucky** [comment]
This is done intentionally. A HPA is created for all components without metrics even if syntax does not have autoscaling specified. The a user can export the policies for a cell instance in yaml format, or create a new one and update using the apply policy command.

**Comment by sinthuja** [comment]
Since the default HPA policies we have created has max and min replica's 1, it's kind of static policy. And hence more and more policies added to the system, the load of the system is also increased to collect the metrics. Therefore, IMHO we shouldn't add default policy unless otherwise it's specified by the user. And export policy command, we should simply say no policies found when there is no auto scaling policy attached to it.

**Comment by isurulucky** [comment]
Fixed with PRs https://github.com/wso2-cellery/sdk/pull/458, https://github.com/wso2-cellery/mesh-controller/pull/77.
