### ISSUE TITLE
Create single script for install artefacts

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#46]
**Description:**
Though we have Make file to build the repo, there copy-libs-<os>.sh and build.sh needs to be executed to copy and install the files in necessary locations. Let's have a single sh file, or have a seperate target in make-file, which builds and installs both lang and cli components.

**Comment by anuruddhal** [comment]
Fixed via
https://github.com/wso2-cellery/sdk/pull/80
