### ISSUE TITLE
Pet-store user information form not getting prompted

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#462]
**Description:**
Previously when signing to pet-store user was prompted to submit his information, i.e first name, last name and address during the initial signing in. Now the users get signed in without submitting those information during the initial signing in.

**Suggested Labels:**
Broken

**Suggested Assignees:**
Nadun

**Affected Product Version:**
Latest build

**OS, DB, other environment details and versions:**    
Tested in local complete setup

**Steps to reproduce:**
* Run pet-sote back end and front end cells
* Go to pet-store web page
* Sign in and check if the user information is requested.

**Comment by nadundesilva** [comment]
The swagger used in the test-cases was old and it was missing an API. This caused the error.

Fixed in #463 by upgrading the swagger
