### ISSUE TITLE
Update the error message when trying to override autoscale policy with overridable = false

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#482]
My component's autoscale policy has overridable false, and hence I cannot apply policy in the runtime as expected. But the below is the error message that is returned during this operation, which doesn't explicitly say about this. 

```
sinthuja@sinthujawso2com:~/wso2/git/wso2-cellery/samples/cells/pet-store/pet-be$ cellery apply-policy autoscale pet-be-policy.yaml pet-be
❌ Preparing to apply autoscale policies


Unable to apply autoscale policies to instance pet-be: No autoscale policies can be updated in cell instance pet-be
```
It will be better to add some context information to the error message, stating that the component policy can't be overridden or similar.

**Comment by isurulucky** [comment]
Fixed in PR: https://github.com/wso2-cellery/sdk/pull/487.
