### ISSUE TITLE
Cell updated is not working as expected

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#492]
I ran hello-world web cell, and then I did some modifications to the env variables. Then I build again, and executed cellery update. Below error was returned.
```
cellery update hello wso2cellery/hello-world-cell:1.0.1
❌ Updating cell components


Unable to apply autoscale policies to instance hello: error unmarshaling JSON: json: Unmarshal(non-pointer kubectl.Cell)
```

**Comment by isurulucky** [comment]
Fixed in https://github.com/wso2-cellery/sdk/pull/498.
