### ISSUE TITLE
Cellery route-traffic didn't work when routing the traffic for second time

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#495]
Steps:
1) I had pet-fe and pet-be cell running as per pet-store sample
2) I started pet-be-v101 cell instance from wso2cellery/pet-fe-cell:1.0.1 image
3) I switched the traffic 100% for pet-be-v101 from pet-be cell, made sure application is working.
4) I terminated the original cell pet-be cell. 
5) Now started pet-be-v102 cell instance from wso2cellery/pet-fe-cell:1.0.2 image
6)  I switched the traffic 100% for pet-be-v102 from pet-be-v101 cell, made sure application is working.
7)  I terminated the cell pet-be-v101 cell, and the application stopped working.

**Comment by isurulucky** [comment]
Fixed in https://github.com/wso2-cellery/sdk/pull/501.
