### ISSUE TITLE
Reinstalling the cellery without uninstalling causing an issue - native function not available 

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#535]
Steps to reproduce.
1) Have previous cellery 0.2.1 installation
2) Now install cellery 0.3.0, without uninstalling the pervious script with ./uninstall.sh
3) Now perform cellery run or celllery build. Below error will be prompted.
```
~/cellerytest/hello$ cellery build hello.bal pzfreo/hello:0.3.0
❌ Building image pzfreo/hello:0.3.0


Build Failed.
======================
error: failed to compile file: native function not available celleryio/cellery:0.0.0:runInstances


Error occurred while building cell image: exit status 1
```

**Comment by gnudeep** [comment]
pkg and deb installer now clean stale cellery-<version>.jar before installing new jar.
