### ISSUE TITLE
Add versioning to APIs deployed in cells

### ISSUE THREAD

**Issue by pzfreo** [wso2-cellery/sdk#538]
**Description:**
A key part of the CBA is that cells should have well-defined interfaces. This means that the swaggers or gRPC proto definitions for a cell need to have version numbers associated.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isurulucky** [comment]
Api versioning is available with 0.4.
