### ISSUE TITLE
Update Ballerina to jBallerina 1.0

### ISSUE THREAD

**Issue by pzfreo** [wso2-cellery/sdk#540]
**Description:**
jBallerina 1.0 is coming out in the next month or so. Cellery should upgrade to support this.

This issue has to perform multiple tasks.

- [x] Migrate cellery sdk to ballerina 1.0
- [x] Migrate cellery testing to ballerina 1.0
- [x] Update cellery-ballerina docker image to work with ballerina 1.0
- [x] Update the installers to work with ballerina 1.0
- [x] Update the cellery CLI to work with 1.0 to resolve path, etc
- [x] Update documentation, and samples. 

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
0.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sinthuja** [comment]
This issue has to perform multiple tasks.

- [ ] Migrate cellery sdk to ballerina 1.0
- [ ] Migrate cellery testing to ballerina 1.0
- [ ] Update cellery-ballerina docker image to work with ballerina 1.0
- [ ] Update the installers to work with ballerina 1.0
- [ ] Update the cellery CLI to work with 1.0 to resolve path, etc
- [ ] Update documentation, and samples.

**Comment by anuruddhal** [comment]
Depends on https://github.com/wso2-cellery/sdk/issues/540
