### ISSUE TITLE
[Intermittent]Download progress bar exceeds 100%

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#585]
**Description:**
When creating cellery local setup, the download progress bar exceeds 100%. This happens intermittently when the download fails in the middle.
![progress-bar](https://user-images.githubusercontent.com/39085607/61606128-6d2fc680-ac66-11e9-8c0f-dd6d4e68e02c.png)

**Suggested Labels:**
Random issue

**Suggested Assignees:**
Madhuka

**Affected Product Version:**
0.3.0

**OS, DB, other environment details and versions:**    
Mac

**Steps to reproduce:**
1. Execute `cellery setup`.
2. Go to create -> local -> complete
3. Confirm the download.
4. Check if the progress bar exceeds 100%.

**Comment by chanakaudaya** [comment]
The same issue happened to me when trying to install the cellery local setup with 0.3.0 version.
