### ISSUE TITLE
[CLI] Improve the CLI to download the VM image efficiently 

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#587]
Currently the local VM is getting downloaded every time when the local setup is getting created. We need to improve this such as if the VM image is downloaded already, and there is no new updated image available for the particular version, then don't download it, and use already existing image.

**Comment by MadhukaHarith92** [comment]
* Additionally local setup cleanup should also get updated.
* When the user execute `cellery setup-> manage-> local -> cleanup` cli should prompt a message requesting whether to delete the downloaded image file or to keep it.
