### ISSUE TITLE
[Cellery Setup] Provide the Nodeport IP optionally for existing cluster setup

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#588]
I was trying to setup with microk8s, and the NodePort IP was (192.168.2.1) different from the list we have by default. Therefore, we should be able to optionally provide the NodePort to be used in the cellery setup, if not the default it used.

**Comment by nadundesilva** [comment]
Even in Minikube v1.2.0, the IP changes (when you delete and recreate the cluster the IP seems to change).

Having a static list of IPs is not a proper solution for using the existing cluster option in `cellery setup`
