### ISSUE TITLE
Unable to add Enduser claims to JWT

### ISSUE THREAD

**Issue by Aaquiff** [wso2-cellery/sdk#606]
**Description:**
It is not possible to add a claim in addition to the claims currently supported by the JWT in cellery's global API gateway. Since the service I am working on validates the JWT using the email of the enduser, the request fails.

I tried to configure the API gateway to pass the Enduser attributes by writing a CustomTokenGenerator[1], however I believe this overrides the cellery token generator which causes problems. This also involves changing the api-manager.xml asl well which means changing the config-maps deployed by cellery runtime itself.

[1] https://docs.wso2.com/display/AM260/Passing+Enduser+Attributes+to+the+Backend+Using+JWT

**Comment by hasinthaindrajee** [comment]
Fixed with https://github.com/wso2-cellery/mesh-security/pull/90
