### ISSUE TITLE
Error when setting up cellery with minikube

### ISSUE THREAD

**Issue by chanakaudaya** [wso2-cellery/sdk#612]
**Description:**
Getting the below mentioned error when trying to install cellery on an already running kubernetes cluster (minikube).

```
Chanakaf:hello-world-api chanaka$ cellery setup
✔ Create
✔ Existing cluster
✔ Persistent volume
✔ No
✔ Complete
✔ Node port [kubeadm, minikube]
✔ Creating cellery runtime
✔ Setting up cellery namespace
✔ Applying istio crds
✔ Creating ingress-nginx
✔ Enabling istio injection
⠴ Installing istioerror: error validating "/Library/Cellery/k8s-artefacts/system/istio-demo-cellery.yaml": error validating data: unknown object type "nil" in kubernetesenv.spec; if you choose to ignore these errors, turn validation off with --validate=false


Failed to deploy cellery runtime: error installing istio: exit status 1
```

**Suggested Labels:**
Bug

**Affected Product Version:**
Cellery 0.3.0

**OS, DB, other environment details and versions:**    
OS Mac OS Mojave
minikube v1.2.0
kubernetes v1.15.0
Docker 18.09.6

**Steps to reproduce:**
- Start minikube
- Cellery setup -> existing cluster -> persistent volume -> NFS (No) -> Full

**Comment by Mirage20** [comment]
@chanakaudaya Can you try with kubernetes v1.14.x? 
For the Cellery v0.3.0, we use Istio 1.0.2 which is not tested on kubernetes v1.15.0

Related: https://github.com/istio/istio/issues/15130

**Comment by sinthuja** [comment]
Let's verify whether minikube is working for 0.5 release.

**Comment by Mirage20** [comment]
Tested with 0.4 release and setup works fine with minikube.
