### ISSUE TITLE
Enabling observability fails when installing cellery on existing cluster and GCP

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#665]
**Description:**
When setting up cellery runtime on an existing cluster or gcp following error occurs.
`the namespace from the provided object "istio-system" does not match the namespace "cellery-system". You must pass '--namespace=istio-system' to perform this operation.
`
This also occurs when modifying a cellery basic runtime when enabling observability.

**Affected Product Version:**
Latest SDK.

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Execute the command `cellery setup`
2. Select `create`-> `Existing cluster`
3. Confirm and install cellery runtime.
4. Wait for the runtime to be ready.

**Comment by MadhukaHarith92** [comment]
@HasithaAthukorala please note.

**Comment by HasithaAthukorala** [comment]
Fixed by #674

**Comment by nadundesilva** [comment]
Closing as per the above comment.
