### ISSUE TITLE
Cell deletions not working sometimes

### ISSUE THREAD

**Issue by Mirage20** [wso2-cellery/sdk#722]
In Docker-for-Mac the cell and related pods won't get deleted due to a pending finalizer "foregroundDeletion" which is related to the k8s garbage collector. Currently, this is not reproducible.

**Comment by sinthuja** [comment]
This is mainly because of the difference in the kubectl version, once the kubectl version is upgraded to 1.14 upwards this problem is no longer there. We need to emphasise this the readme.

**Comment by sinthuja** [comment]
Fixed with https://github.com/wso2-cellery/sdk/commit/63b19dc65583abd8f0dcd3aa3d463e017623b22a
