### ISSUE TITLE
Cellery run command fails in docker for desktop

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#723]
**Description:**
When starting a cell instance by executing `cellery run` command, a failure occurs.

cellery run pzfreo/hello:0.4.0
✔
 Extracting Cell Image pzfreo/hello:0.4.0
✔
 Reading Image pzfreo/hello:0.4.0
ballerina: insufficient arguments to call the 'main' function
⠼ Starting main instance

Failed to start Cell instance : failed to execute run method in Cell instance  due to exit status 1

**Affected Product Version:**
0.4.0-RC

**OS, DB, other environment details and versions:**    
Docker for desktop

**Steps to reproduce:**
1. Execute `cellery init` command.
2. Build the cell using `cellery build` command.
3. Run the cell using `cellery run` command.

**Comment by sinthuja** [comment]
Verified in Sep-30th build
