### ISSUE TITLE
Cellery install doesn't create a ~/.cellery/gcp directory 

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#724]
**Description:**
Cellery install doesn't create a ~/.cellery/gcp directory 

**Affected Product Version:**
0.4.0-RC

**OS, DB, other environment details and versions:**    
Docker for desktop

**Steps to reproduce:**
1. Remove ~/.cellery/gcp if already exists.
2. Install cellery by downloading the .pkg (https://wso2.org/jenkins/job/cellery/job/sdk/)
3. Check if ~/.cellery/gcp directory is getting created.

**Comment by azinneera** [comment]
The cellery installer runs on sudo mode and hence it does not know about the user home in which the .cellery directory has to be created. IMO, this has be done within the root command of the CLI.
