### ISSUE TITLE
Extensive logs while pulling non existing image

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2-cellery/sdk#730]
**Description:**
Extensive amount of logs are printed stating the status if image pulling when cells are started with non existing dependency cells. 

**Steps to reproduce:**
1) Delete wso2cellery/pet-be-cell:latest-dev image if you have it in the local repository.
2) cellery run wso2cellery/pet-fe-cell:latest-dev -n pet-fe -l petStoreBackend:pet-be -d

**Comment by sinthuja** [comment]
The issue still exists when pulling composites, it's resolved for cells.

cellery run wso2cellery/pet-fe-comp-cell:latest-dev -n pet-fe-comp-cell-inst -d
✔ Connecting to registry.hub.cellery.io
✔ Fetching metadata
✔ Pulling image wso2cellery/pet-fe-comp-cell:latest-dev
✔ Removing old Image
✔ Saving new Image to the Local Repository

Image Digest : sha256:7875d04057cb708ee9109075fc7f68e00522e7e5cd42b57a0e74807a48625f3f

✔ Extracting Cell Image wso2cellery/pet-fe-comp-cell:latest-dev
✔ Reading Image wso2cellery/pet-fe-comp-cell:latest-dev
Info: Main Instance: pet-fe-comp-cell-inst
Info: Validating dependencies
Info: Instances to be Used
------------------------------------------------------------------------------------------------------------------------
INSTANCE NAME                  CELL IMAGE                          USED INSTANCE             KIND            SHARED
------------------------------------------------------------------------------------------------------------------------
pet-be-complatest-dev1248      wso2cellery/pet-be-comp:latest-dev  To be Created             Composite       -
pet-fe-comp-cell-inst          wso2cellery/pet-fe-comp-cell:latest-dev To be Created             Cell            -
------------------------------------------------------------------------------------------------------------------------
Info: Dependency Tree to be Used

pet-fe-comp-cell-inst
└── petStoreBackend:pet-be-complatest-dev1248

Info:
      ⠋ Connecting to registry.hub.cellery.io
      ⠙ Connecting to registry.hub.cellery.io
      ⠹ Connecting to registry.hub.cellery.io
      ⠸ Connecting to registry.hub.cellery.io
      ⠼ Connecting to registry.hub.cellery.io
      ⠴ Connecting to registry.hub.cellery.io
      ⠦ Connecting to registry.hub.cellery.io
      ⠧ Connecting to registry.hub.cellery.io
      ⠇ Connecting to registry.hub.cellery.io
      ⠏ Connecting to registry.hub.cellery.io
      ⠋ Connecting to registry.hub.cellery.io
      ⠙ Connecting to registry.hub.cellery.io
      ⠹ Connecting to registry.hub.cellery.io
      ⠸ Connecting to registry.hub.cellery.io
      ⠼ Connecting to registry.hub.cellery.io
      ⠴ Connecting to registry.hub.cellery.io
      ⠦ Connecting to registry.hub.cellery.io
      ⠧ Connecting to registry.hub.cellery.io
      ⠇ Connecting to registry.hub.cellery.io
      ⠏ Connecting to registry.hub.cellery.io
      ⠋ Connecting to registry.hub.cellery.io
      ⠙ Connecting to registry.hub.cellery.io
      ⠹ Connecting to registry.hub.cellery.io
      ⠸ Connecting to registry.hub.cellery.io
      ⠼ Connecting to registry.hub.cellery.io
      ⠴ Connecting to registry.hub.cellery.io
      ✔ Connecting to registry.hub.cellery.io
Info:
      ⠦ Fetching metadata
      ⠧ Fetching metadata
      ⠇ Fetching metadata
      ⠏ Fetching metadata
      ⠋ Fetching metadata
      ⠙ Fetching metadata
      ⠹ Fetching metadata
      ⠸ Fetching metadata
      ⠼ Fetching metadata
      ⠴ Fetching metadata
      ✔ Fetching metadata
Info:
      ⠦ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠧ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠇ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠏ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠋ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠙ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠹ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠸ Pulling image wso2cellery/pet-be-comp:latest-dev
      ⠼ Pulling image wso2cellery/pet-be-comp:latest-dev
      ✔ Pulling image wso2cellery/pet-be-comp:latest-dev
Info:
      ⠴ Removing old Image
      ✔ Removing old Image
Info:
      ⠦ Saving new Image to the Local Repository
      ✔ Saving new Image to the Local Repository
Info:
Info: Image Digest : sha256:c32056cedd32b8432600c7360142484cefcf59de8ceddaad49e7e2b7c42768bb
Info:
Info:
Info: ✔ Successfully pulled cell image: registry.hub.cellery.io/wso2cellery/pet-be-comp:latest-dev
Info:
Info: What's next?
Info: --------------------------------------------------------
Info: Execute the following command to run the image:
Info:   $ cellery run registry.hub.cellery.io/wso2cellery/pet-be-comp:latest-dev
Info: --------------------------------------------------------
Info:
Info: starting instance pet-be-complatest-dev1248
✔ Starting main instance pet-fe-comp-cell-inst


✔ Successfully deployed cell image: wso2cellery/pet-fe-comp-cell:latest-dev

What's next?
--------------------------------------------------------
Execute the following command to list running cells:
  $ cellery list instances
--------------------------------------------------------

**Comment by anuruddhal** [comment]
Are you using the latest SDK? This is working as expected with the latest SDK.

```bash
cellery run wso2cellery/pet-fe-comp-cell:latest-dev -n pet-fe-comp-cell-inst -d
✔ Connecting to registry.hub.cellery.io
✔ Fetching metadata
✔ Pulling image wso2cellery/pet-fe-comp-cell:latest-dev
✔ Removing old Image
✔ Saving new Image to the Local Repository

Image Digest : sha256:719d93a1bc2e78041e5117b029ebb8b50b7697e7a28cd53257dd2159176500f5

✔ Extracting Cell Image wso2cellery/pet-fe-comp-cell:latest-dev
✔ Reading Image wso2cellery/pet-fe-comp-cell:latest-dev
Info: Main Instance: pet-fe-comp-cell-inst
Info: Validating dependencies
Info: Instances to be Used
------------------------------------------------------------------------------------------------------------------------
INSTANCE NAME                  CELL IMAGE                          USED INSTANCE             KIND            SHARED
------------------------------------------------------------------------------------------------------------------------
pet-be-complatest-dev6pl5      wso2cellery/pet-be-comp:latest-dev  To be Created             Composite       -
pet-fe-comp-cell-inst          wso2cellery/pet-fe-comp-cell:latest-dev To be Created             Cell            -
------------------------------------------------------------------------------------------------------------------------
Info: Dependency Tree to be Used

pet-fe-comp-cell-inst
└── petStoreBackend:pet-be-complatest-dev6pl5

Info: starting instance pet-be-complatest-dev6pl5 f8ca859d424404cbe4e3808ef3973dc1dc169095f5
✔ Starting main instance pet-fe-comp-cell-inst


✔ Successfully deployed cell image: wso2cellery/pet-fe-comp-cell:latest-dev

What's next?
--------------------------------------------------------
Execute the following command to list running cells:
  $ cellery list instances
--------------------------------------------------------
```

**Comment by hasinthaindrajee** [comment]
@anuruddhal : Just an additional question, this log doesn't say that pet-be cell is not present and hence it's pulling the image from hub. Don't we need to show it as well ?. In my original issue, that was the case I was trying.

**Comment by anuruddhal** [comment]
@hasinthaindrajee Added more logs via https://github.com/wso2-cellery/sdk/commit/7acd6620716eeb10d67065f000cecc8e3c31585e

**Comment by sinthuja** [comment]
I was using some latest build as of yesterday. However, I downloaded the today's build as of 1:33PM LKT, and it's working with this. Therefore, we can resolve the original problem. Thanks.
