### ISSUE TITLE
HPA auto scaling fails with pet store sample. 

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2-cellery/sdk#736]
**Description:**
Followed the sample steps in https://github.com/wso2-cellery/samples/blob/master/docs/pet-store/scale-cell.md

I was using the image which is in Cellery Hub (https://hub.cellery.io/images/wso2cellery/pet-be-auto-scale-cell/latest-dev)

controller starts to autoscale. But immediately pods go to terminating state. 

pet-be--controller-deployment-57747c6654-7pggz                  0/2       Terminating   0          7s
pet-be--controller-deployment-57747c6654-992k7                  2/2       Running       0          23m

As per observations this is due to having replicas count as 1 in controller. When the scaling starts cellery controller brings it back to replicas 1.

**Comment by isurulucky** [comment]
Closing since this should be resolved by https://github.com/wso2-cellery/mesh-controller/pull/132. Please re-open if required.
