### ISSUE TITLE
Incorrect error message returned when there is no test to exectute

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#737]
✔ Extracting Cell Image sinthuja/hello-world-project:0.4.0-rc
✔ Reading Image sinthuja/hello-world-project:0.4.0-rc

✔ Starting execution of tests for sinthuja/hello-world-project:0.4.0-rc...

Failed to test Cell instance : error occurred while initializing ballerina project for tests%!(EXTRA *exec.Error=exec: "ballerina": executable file not found in $PATH)

The above image doesn't have test, and hence it should simply throw an error stating that there is no tests for the cell.

**Comment by azinneera** [comment]
Resolved
