### ISSUE TITLE
Error while executing cellery test

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#750]
cellery test wso2cellery/pet-be-cell:latest-dev -n pet-be
✔ Extracting Cell Image wso2cellery/pet-be-cell:latest-dev
✔ Reading Image wso2cellery/pet-be-cell:latest-dev

✔ Starting execution of tests for wso2cellery/pet-be-cell:latest-dev...
? Do you wish to continue with testing above Cell instances (Y/n)?
⠋ Creating telepresence instance

error waiting for telepresence deployment telepresence--telepresence-deployment to be available: exit status 1

Environment: docker-for-mac

**Comment by azinneera** [comment]
Resolved
