### ISSUE TITLE
[Observability]Cannot search for tracing data 

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#755]
Environment: Docker-for-mac, and ballerina installed.

Steps to reproduce: Installed multiple instance of pet-store cell and observability worked, and then after some time, deployed hello world composite (https://github.com/wso2-cellery/samples/tree/master/composites/hello-world), and the dependency model wasn't generated. And then when I searched the distributed tracing, I got StackOverflow error, and the results wasn't returned. 

Attaching the SP server logs, and DB dump. 
[tracing-issue.zip](https://github.com/wso2-cellery/sdk/files/3677938/tracing-issue.zip)

**Comment by nadundesilva** [comment]
The tracing search issue seems to be due to the way we are searching for data. One of the queries gets too big for antlr to parse in Siddhi. We can avoid this by implementing a limit and offset method for search results.

**Comment by sinthuja** [comment]
+1 for implementing the limit and offset. Let me try the hello world composite again to narrow down the dependency model problem.
