### ISSUE TITLE
Unable to route traffic to the target composite instance

### ISSUE THREAD

**Issue by Minoli** [wso2-cellery/sdk#759]
**Description:**
In pet-store composite cell sample when doing Blue-Green and Canary deployment following error occured. Seems like the issue is intermittent as it was successful on the first routing.

<img width="1001" alt="Screen Shot 2019-10-02 at 12 10 01 PM" src="https://user-images.githubusercontent.com/9837443/66024553-c1caaa00-e511-11e9-8b83-6f3befc606f7.png">

**Comment by isurulucky** [comment]
PR https://github.com/wso2-cellery/sdk/pull/761 fixes the suspected issue while reading kubectl output from commandline.
