### ISSUE TITLE
Improve message when route-traffic is aborted without matching version.

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2-cellery/sdk#773]
**Description:**
When traffic is routed to a different cell which has a different ingress version, it asks for a confirmation. When the confirmation is denied it gives a message with a **Red Cross**. Should it be a red cross since nothing had gone wrong ?

cellery route-traffic -d pet-be -t pet-be-versioned -p 50
✔ Starting to route 50% of traffic to instance pet-be-versioned

⚠ No matching API found in target for context: '/controller', version: ''. Available version in target: '2.1.0' 

✔ No
❌ Building modified rules

**Steps to reproduce:**
Deploy pet-store sample. 
Create another cell with a different version of controller ingress
Try to route traffic to new cell.

**Comment by isurulucky** [comment]
![image](https://user-images.githubusercontent.com/2777052/66106602-e3906380-e5db-11e9-99dc-4e93154d7fa9.png)
@hasinthaindrajee
