### ISSUE TITLE
Cellery command to list reference.json

### ISSUE THREAD

**Issue by himasha** [wso2-cellery/sdk#820]
**Description:**
In order to find out the ingresskey of a reference cell (where the source code is not available and is pulled from the cellery hub) , there is a need for a CLI command to list those references of the cell.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.4
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by himasha** [comment]
Yes, that option sounds good since we already have a command to list ingress.

**Comment by tharindulak** [comment]
This was fixed by #863. Now we can view ingress keys for an image.

**Comment by nadundesilva** [comment]
Closing as per the above comment.
