### ISSUE TITLE
Create brew based installer for Mac

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#822]
**Description:**
Currently cellery mac installation is supported with pkg, but this has some limitations where pre-requisites (docker, tele presence, etc) of cellery cannot be auto-deployed. Brew is a the well known package management for mac, and it allows to have dependency packages in the installer. Therefore, for cellery we should support brew installer, and incorporate the pre-requisites for docker, tele presence, etc in it.

**Comment by hasinthaindrajee** [comment]
Updated the versions with https://github.com/Homebrew/homebrew-cask/pull/72781
