### ISSUE TITLE
CLI re-factor and re-archiecture

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#829]
**Description:**
Current CLI doesn't support test driven development, and we need to refactor the code to support that. Further the code is not very friendly to support reusability, and extensibility, therefore re-architect to support these aspects.

**Comment by isurulucky** [comment]
Except setup, login and route-traffic commands, others are completed. Remaining work tracked in https://github.com/wso2-cellery/sdk/issues/926.
