### ISSUE TITLE
404 response for a global API having the same context name as the requesting resource path name

### ISSUE THREAD

**Issue by himasha** [wso2-cellery/sdk#830]
**Description:**
Create a Cell with a HTTP API deployed on the global gateway with the context set to 'reviews'.
Now invoking a resource named 'reviews' similar to below https://wso2-apim-gateway/review-inst/reviews/0.1/reviews would give a 404. 
This same API would work as expected with a different context such as 'reviewsctx'. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.4
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madushajg** [comment]
Here you have configured the global context inside globalPublisher as 'reviews'. Hence you have to invoke  https://wso2-apim-gateway/reviews/reviews/0.1/reviews as mentioned in the [API versioning doc](https://github.com/wso2-cellery/sdk/blob/master/docs/cellery-syntax.md#expose).
Here, the First review is coming from globalPublisher, second is from cellery:HttpApiIngress and the third is from path under the cellery:HttpApiIngress, resources.

**Comment by himasha** [comment]
Hi Madusha, 
I haven't added the global publisher configuration as mentioned in the provided doc. Attaching the bal  file content for reference. 
[product-review.txt](https://github.com/wso2-cellery/sdk/files/3754332/product-review.txt)

**Comment by madushajg** [comment]
Hi Himasha,
I couldn't reproduce this with available samples. Can you please provide the sample that you are trying?

**Comment by tharindulak** [comment]
I also tried with the above-mentioned scenario, I also could not reproduce the issue.
