### ISSUE TITLE
Readme QSG list a hardcoded IP

### ISSUE THREAD

**Issue by nirmal070125** [wso2-cellery/sdk#831]
**Description:**

Under https://github.com/wso2-cellery/sdk#hello-world-with-cellery
```
3. Add the following line to the /etc/hosts file.

  192.168.56.10 hello-world.com
```
Hardcoded IP is a typo right?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sinthuja** [comment]
Hi Nirmal,

QSG focuses on the steps that are required to be followed for local setup of Cellery (ie, local VM download), and hence the instruction is right. However, I understand that this may confuse the users who have installed cellery in different k8s cluster other than local. I'll add a explaination about this, and provide the links to respective sections on adding the correct /etc/host values. 

Thanks for reporting the issue.

**Comment by sinthuja** [comment]
Fixed this issue.
