### ISSUE TITLE
A failed setup does not rollback changes and leave the cluster with partial installation preventing new installs

### ISSUE THREAD

**Issue by joaoemilio** [wso2-cellery/sdk#885]
**Description:**
A failed setup does not rollback changes and leave the cluster with partial installation preventing new setup.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Cellery 0.4

**OS, DB, other environment details and versions:**    
MacOS 10.14.6
Docker for Mac

**Steps to reproduce:**
MacBook-Joao:~ joaoemilio$ cellery setup
✔ Create
✔ Existing cluster
✔ Non persistent volume
✔ Basic
✔ Load balancer [gcp, docker for desktop]
✔ Creating cellery runtime
✔ Setting up cellery namespace
✔ Applying istio crds
✔ Creating ingress-nginx
✔ Enabling istio injection
✔ Installing istio
✔ Creating controller
⠋ Configuring mysqlError from server (AlreadyExists): configmaps "mysql-dbscripts" already exists

Failed to deploy cellery runtime: error configuring mysql: exit status 1

MacBook-Joao:~ joaoemilio$ 

**Related Issues:**
#884 #883

**Comment by nadundesilva** [comment]
Can you try to delete `cellery-system` namespace and try again ?

`kubectl delete ns cellery-system`

@MadhukaHarith92 can we try to handle this on our end ?

**Comment by joaoemilio** [comment]
Hi @nadundesilva , by deleting the namespace I was able to run the setup again. Thanks.

**Comment by joaoemilio** [comment]
One additional ask. Where can I check logs for the cellery setup or any other cellery commands?

**Comment by MadhukaHarith92** [comment]
Hi @joaoemilio , an issue for this is already created in https://github.com/wso2-cellery/sdk/issues/818
This will be handled in future.

**Comment by nadundesilva** [comment]
We do have additional logs in `~/.cellery/logs/cli.log` file.

However, this log needs to be improved.

**Comment by nadundesilva** [comment]
Closing as this is a duplicate
