### ISSUE TITLE
Cell gets ready before the Cell STS is ready

### ISSUE THREAD

**Issue by nadundesilva** [wso2-cellery/sdk#909]
**Description:**
At the moment, the `Ready` condition in the Cell is changed to true, before the STS deployment gets ready. This can be troublesome if the user tries to invoke an API when the STS is still starting up.

**Note:** Also Cell does not wait for the global API publisher as well. This is ok as the Cell itself is functional at this point.

**Comment by MadhukaHarith92** [comment]
Cell testing encountered a problem due to this issue. It was fixed in the SDK (https://github.com/wso2-cellery/sdk/pull/927). Please revert this fix once the improvement is properly done in the controller.

**Comment by nadundesilva** [comment]
Also we need to add proper readiness and liveness probes to the STS as well.

**Comment by Mirage20** [comment]
Resolves with https://github.com/wso2-cellery/mesh-controller/pull/142

**Comment by Mirage20** [comment]
> Cell testing encountered a problem due to this issue. It was fixed in the SDK (#927). Please revert this fix once the improvement is properly done in the controller.

This is reverted with https://github.com/wso2-cellery/sdk/pull/957
