### ISSUE TITLE
[intermittent] Tests fail for pet backend cell

### ISSUE THREAD

**Issue by Minoli** [wso2-cellery/sdk#922]
**Description:**
When running 'cellery test wso2cellery/pet-be-cell:latest' command the mvn build and tests fails intermittently. 

<img width="1077" alt="Screen Shot 2019-11-15 at 11 29 53 AM" src="https://user-images.githubusercontent.com/9837443/68928272-b07ee980-07af-11ea-8bfa-ca3771745540.png">
<img width="1232" alt="Screen Shot 2019-11-15 at 1 54 19 PM" src="https://user-images.githubusercontent.com/9837443/68928290-b96fbb00-07af-11ea-8491-8250df6d3f68.png">

***Error logs***

Minolis-MacBook-Pro:~ minta$ kubectl logs pet-be-celllatest2foq--controller-deployment-65594b7df4-xjlsn controller  -f
[INFO] Pet Store Controller Service listening at http://:::80
[ERROR] Failed to fetch orders data due to TypeError: Cannot read property 'map' of undefined
[ERROR] GET /orders 500 193.954 ms - 116
[INFO] Shutting down Pet Store Controller Service
[INFO] Pet Store Controller Service shutdown complete

------------------------------------------------------------------------------------------------

root@pet-be-celllatest2foq--controller-deployment-65594b7df4-xjlsn:/service# tail -f log/access.log
::ffff:127.0.0.1 - - [15/Nov/2019:06:15:46 +0000] "POST /orders HTTP/1.1" 200 36 "-" "ballerina/1.0.3"
::ffff:127.0.0.1 - - [15/Nov/2019:06:18:50 +0000] "POST /orders HTTP/1.1" 200 36 "-" "Apache-HttpClient/4.5.6 (Java/1.8.0_212)"
::ffff:127.0.0.1 - - [15/Nov/2019:06:18:50 +0000] "GET /orders HTTP/1.1" 500 116 "-" "Apache-HttpClient/4.5.6 (Java/1.8.0_212)"
command terminated with exit code 137

**Comment by azinneera** [comment]
Resolved.
